parameters:
  azureSubscription:
  storageAccountRg:
  storageAccountName:
  storageAccountKey:
  rg:
  loc:
  workingDirectory:

jobs:
- job: Deploy
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  # Terraform Init
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: ${{ parameters.azureSubscription }}
      backendAzureRmResourceGroupName: ${{ parameters.storageAccountRg }}
      backendAzureRmStorageAccountName: ${{ parameters.storageAccountName }}
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: ${{ parameters.storageAccountKey }}
      workingDirectory: ${{ parameters.workingDirectory }}

  # Terraform plan
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: ${{ parameters.azureSubscription }}
      workingDirectory: ${{ parameters.workingDirectory }}

  # Terraform apply
  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: ${{ parameters.azureSubscription }}
      workingDirectory: ${{ parameters.workingDirectory }}