trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Demo$/*
    - azure-pipelines-demo4.yml
    - azure-pipelines-terraform-release.yml

pr:
  autoCancel: true
 
variables:
  sandboxAzureSubscription: 'MTC Denver Sandbox'
  productionAzureSubscription: 'MTC Denver Production'
  storageAccountRg: demo-terraform-sandbox-rg
  storageAccountName: mtcdenterraformsandbox
  workingDirectory: '$(System.DefaultWorkingDirectory)/Demo4'
  location: 'West US 2'
  name: hashiconf-demo4

stages:

# Deploy to Staging
- stage: Staging
  jobs:
  - template: azure-pipelines-terraform-release.yml
    parameters:
      storageAccountRg: $(storageAccountRg)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(sandboxAzureSubscription)
      workingDirectory: $(workingDirectory)
      name: '$(name)'
      environment: 'staging'
      

# Deploy to Production
- stage: Production
  jobs:
  - template: azure-pipelines-terraform-release.yml
    parameters:
      storageAccountRg: $(storageAccountRg)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(productionAzureSubscription)
      workingDirectory: $(workingDirectory)
      name: '$(name)'
      environment: 'production'
      