trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Demo2/*
    - azure-pipelines-demo2.yml
    - azure-pipelines-terraform-release.yml

pr:
  autoCancel: true
 
variables:
  sandboxAzureSubscription: 'MTC Denver Sandbox'
  productionAzureSubscription: 'MTC Denver Production'
  storageAccountRg: demo-terraform-sandbox-rg
  storageAccountName: mtcdenterraformsandbox
  workingDirectory: '$(System.DefaultWorkingDirectory)/Demo2'
  location: 'West US 2'
  name: demo2

stages:

# Deploy to Staging
- stage: Staging
  jobs:
  - template: azure-pipelines-terraform-release.yml
    parameters:
      storageAccountRg: $(storageAccountRg)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(sandboxAzureSubscription)
      workingDirectory: $(workingDirectory)
      loc: $(location)
      rg: 'hashiconf-$(name)-staging-rg'
      

# Deploy to Production
- stage: Production
  jobs:
  - template: azure-pipelines-terraform-release.yml
    parameters:
      storageAccountRg: $(storageAccountRg)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(productionAzureSubscription)
      workingDirectory: $(workingDirectory)
      loc: $(location)
      rg: 'hashiconf-$(name)-production-rg'
      