trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Demo3/*
    - azure-pipelines-demo3.yml
    - azure-pipelines-terraform-release.yml

pr:
  autoCancel: true
 
variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/Demo3'
  name: hashiconf-demo3

stages:

# Deploy to Staging
- stage: Staging
  jobs:
  - template: azure-pipelines-terraform-release.yml
    parameters:
      storageAccountRg: $(storageAccountRg)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(sandboxAzureSubscription)
      workingDirectory: $(workingDirectory)
      name: '$(name)'
      environment: 'staging'
      

# Deploy to Production
- stage: Production
  jobs:
  - template: azure-pipelines-terraform-release.yml
    parameters:
      storageAccountRg: $(storageAccountRg)
      storageAccountName: $(storageAccountName)
      storageAccountKey: $(storageAccountKey)
      azureSubscription: $(productionAzureSubscription)
      workingDirectory: $(workingDirectory)
      name: '$(name)'
      environment: 'production'
      